<?php

namespace App\Repository;

/**
 * UsuarioTelefoneRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UsuarioTelefoneRepository extends Repository 
{

}