<?php

namespace App\Repository;

/**
 * UsuarioTokenRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UsuarioTokenRepository extends Repository 
{

}