<?php

namespace App\Repository;

/**
 * UsuarioEnderecoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UsuarioEnderecoRepository extends Repository 
{

}