<?php

namespace App\Repository;

/**
 * UsuarioBiometriaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UsuarioBiometriaRepository extends Repository 
{

}