<?php

namespace App\Proxies\__CG__\App\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class UsuarioToken extends \App\Entity\UsuarioToken implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Proxy\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Proxy\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array<string, null> properties to be lazy loaded, indexed by property name
     */
    public static $lazyPropertiesNames = array (
);

    /**
     * @var array<string, mixed> default values of properties to be lazy loaded, with keys being the property names
     *
     * @see \Doctrine\Common\Proxy\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array (
);



    public function __construct(?\Closure $initializer = null, ?\Closure $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', '' . "\0" . 'App\\Entity\\UsuarioToken' . "\0" . 'idToken', '' . "\0" . 'App\\Entity\\UsuarioToken' . "\0" . 'accessToken', '' . "\0" . 'App\\Entity\\UsuarioToken' . "\0" . 'tempoExpiracao', '' . "\0" . 'App\\Entity\\UsuarioToken' . "\0" . 'tempoGeracao', '' . "\0" . 'App\\Entity\\UsuarioToken' . "\0" . 'dataRegistro', '' . "\0" . 'App\\Entity\\UsuarioToken' . "\0" . 'valido', '' . "\0" . 'App\\Entity\\UsuarioToken' . "\0" . 'usuario'];
        }

        return ['__isInitialized__', '' . "\0" . 'App\\Entity\\UsuarioToken' . "\0" . 'idToken', '' . "\0" . 'App\\Entity\\UsuarioToken' . "\0" . 'accessToken', '' . "\0" . 'App\\Entity\\UsuarioToken' . "\0" . 'tempoExpiracao', '' . "\0" . 'App\\Entity\\UsuarioToken' . "\0" . 'tempoGeracao', '' . "\0" . 'App\\Entity\\UsuarioToken' . "\0" . 'dataRegistro', '' . "\0" . 'App\\Entity\\UsuarioToken' . "\0" . 'valido', '' . "\0" . 'App\\Entity\\UsuarioToken' . "\0" . 'usuario'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (UsuarioToken $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy::$lazyPropertiesDefaults as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @deprecated no longer in use - generated code now relies on internal components rather than generated public API
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getIdToken()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getIdToken();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIdToken', []);

        return parent::getIdToken();
    }

    /**
     * {@inheritDoc}
     */
    public function setIdToken($idToken)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIdToken', [$idToken]);

        return parent::setIdToken($idToken);
    }

    /**
     * {@inheritDoc}
     */
    public function getAccessToken()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAccessToken', []);

        return parent::getAccessToken();
    }

    /**
     * {@inheritDoc}
     */
    public function setAccessToken($accessToken)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setAccessToken', [$accessToken]);

        return parent::setAccessToken($accessToken);
    }

    /**
     * {@inheritDoc}
     */
    public function getTempoExpiracao()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTempoExpiracao', []);

        return parent::getTempoExpiracao();
    }

    /**
     * {@inheritDoc}
     */
    public function setTempoExpiracao($tempoExpiracao)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTempoExpiracao', [$tempoExpiracao]);

        return parent::setTempoExpiracao($tempoExpiracao);
    }

    /**
     * {@inheritDoc}
     */
    public function getTempoGeracao()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTempoGeracao', []);

        return parent::getTempoGeracao();
    }

    /**
     * {@inheritDoc}
     */
    public function setTempoGeracao($tempoGeracao)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTempoGeracao', [$tempoGeracao]);

        return parent::setTempoGeracao($tempoGeracao);
    }

    /**
     * {@inheritDoc}
     */
    public function getDataRegistro()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDataRegistro', []);

        return parent::getDataRegistro();
    }

    /**
     * {@inheritDoc}
     */
    public function setDataRegistro($dataRegistro)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDataRegistro', [$dataRegistro]);

        return parent::setDataRegistro($dataRegistro);
    }

    /**
     * {@inheritDoc}
     */
    public function getValido()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getValido', []);

        return parent::getValido();
    }

    /**
     * {@inheritDoc}
     */
    public function setValido($valido)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setValido', [$valido]);

        return parent::setValido($valido);
    }

    /**
     * {@inheritDoc}
     */
    public function getUsuario()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getUsuario', []);

        return parent::getUsuario();
    }

    /**
     * {@inheritDoc}
     */
    public function setUsuario($usuario)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setUsuario', [$usuario]);

        return parent::setUsuario($usuario);
    }

}
