<?php

namespace App\Proxies\__CG__\App\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class UsuarioEndereco extends \App\Entity\UsuarioEndereco implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Proxy\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Proxy\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array<string, null> properties to be lazy loaded, indexed by property name
     */
    public static $lazyPropertiesNames = array (
);

    /**
     * @var array<string, mixed> default values of properties to be lazy loaded, with keys being the property names
     *
     * @see \Doctrine\Common\Proxy\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array (
);



    public function __construct(?\Closure $initializer = null, ?\Closure $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', '' . "\0" . 'App\\Entity\\UsuarioEndereco' . "\0" . 'idEndereco', '' . "\0" . 'App\\Entity\\UsuarioEndereco' . "\0" . 'descRua', '' . "\0" . 'App\\Entity\\UsuarioEndereco' . "\0" . 'numrEndereco', '' . "\0" . 'App\\Entity\\UsuarioEndereco' . "\0" . 'descComplemento', '' . "\0" . 'App\\Entity\\UsuarioEndereco' . "\0" . 'descBairro', '' . "\0" . 'App\\Entity\\UsuarioEndereco' . "\0" . 'descCidade', '' . "\0" . 'App\\Entity\\UsuarioEndereco' . "\0" . 'descUf', '' . "\0" . 'App\\Entity\\UsuarioEndereco' . "\0" . 'usuario'];
        }

        return ['__isInitialized__', '' . "\0" . 'App\\Entity\\UsuarioEndereco' . "\0" . 'idEndereco', '' . "\0" . 'App\\Entity\\UsuarioEndereco' . "\0" . 'descRua', '' . "\0" . 'App\\Entity\\UsuarioEndereco' . "\0" . 'numrEndereco', '' . "\0" . 'App\\Entity\\UsuarioEndereco' . "\0" . 'descComplemento', '' . "\0" . 'App\\Entity\\UsuarioEndereco' . "\0" . 'descBairro', '' . "\0" . 'App\\Entity\\UsuarioEndereco' . "\0" . 'descCidade', '' . "\0" . 'App\\Entity\\UsuarioEndereco' . "\0" . 'descUf', '' . "\0" . 'App\\Entity\\UsuarioEndereco' . "\0" . 'usuario'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (UsuarioEndereco $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy::$lazyPropertiesDefaults as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @deprecated no longer in use - generated code now relies on internal components rather than generated public API
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getIdEndereco()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getIdEndereco();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIdEndereco', []);

        return parent::getIdEndereco();
    }

    /**
     * {@inheritDoc}
     */
    public function setIdEndereco($idEndereco)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIdEndereco', [$idEndereco]);

        return parent::setIdEndereco($idEndereco);
    }

    /**
     * {@inheritDoc}
     */
    public function getDescRua()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDescRua', []);

        return parent::getDescRua();
    }

    /**
     * {@inheritDoc}
     */
    public function setDescRua($descRua)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDescRua', [$descRua]);

        return parent::setDescRua($descRua);
    }

    /**
     * {@inheritDoc}
     */
    public function getNumrEndereco()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNumrEndereco', []);

        return parent::getNumrEndereco();
    }

    /**
     * {@inheritDoc}
     */
    public function setNumrEndereco($numrEndereco)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNumrEndereco', [$numrEndereco]);

        return parent::setNumrEndereco($numrEndereco);
    }

    /**
     * {@inheritDoc}
     */
    public function getDescComplemento()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDescComplemento', []);

        return parent::getDescComplemento();
    }

    /**
     * {@inheritDoc}
     */
    public function setDescComplemento($descComplemento)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDescComplemento', [$descComplemento]);

        return parent::setDescComplemento($descComplemento);
    }

    /**
     * {@inheritDoc}
     */
    public function getDescBairro()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDescBairro', []);

        return parent::getDescBairro();
    }

    /**
     * {@inheritDoc}
     */
    public function setDescBairro($descBairro)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDescBairro', [$descBairro]);

        return parent::setDescBairro($descBairro);
    }

    /**
     * {@inheritDoc}
     */
    public function getDescCidade()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDescCidade', []);

        return parent::getDescCidade();
    }

    /**
     * {@inheritDoc}
     */
    public function setDescCidade($descCidade)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDescCidade', [$descCidade]);

        return parent::setDescCidade($descCidade);
    }

    /**
     * {@inheritDoc}
     */
    public function getDescUf()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDescUf', []);

        return parent::getDescUf();
    }

    /**
     * {@inheritDoc}
     */
    public function setDescUf($descUf)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDescUf', [$descUf]);

        return parent::setDescUf($descUf);
    }

    /**
     * {@inheritDoc}
     */
    public function getUsuario()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getUsuario', []);

        return parent::getUsuario();
    }

    /**
     * {@inheritDoc}
     */
    public function setUsuario($usuario)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setUsuario', [$usuario]);

        return parent::setUsuario($usuario);
    }

}
