<?php

namespace App\Proxies\__CG__\App\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Usuario extends \App\Entity\Usuario implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Proxy\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Proxy\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array<string, null> properties to be lazy loaded, indexed by property name
     */
    public static $lazyPropertiesNames = array (
);

    /**
     * @var array<string, mixed> default values of properties to be lazy loaded, with keys being the property names
     *
     * @see \Doctrine\Common\Proxy\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array (
);



    public function __construct(?\Closure $initializer = null, ?\Closure $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', '' . "\0" . 'App\\Entity\\Usuario' . "\0" . 'idUsuario', '' . "\0" . 'App\\Entity\\Usuario' . "\0" . 'descNome', '' . "\0" . 'App\\Entity\\Usuario' . "\0" . 'numrCpf', '' . "\0" . 'App\\Entity\\Usuario' . "\0" . 'descEmail', '' . "\0" . 'App\\Entity\\Usuario' . "\0" . 'descSenha', '' . "\0" . 'App\\Entity\\Usuario' . "\0" . 'dataNascimento', '' . "\0" . 'App\\Entity\\Usuario' . "\0" . 'dataRegistro', '' . "\0" . 'App\\Entity\\Usuario' . "\0" . 'enderecos', '' . "\0" . 'App\\Entity\\Usuario' . "\0" . 'biometrias', '' . "\0" . 'App\\Entity\\Usuario' . "\0" . 'telefones', '' . "\0" . 'App\\Entity\\Usuario' . "\0" . 'tokens'];
        }

        return ['__isInitialized__', '' . "\0" . 'App\\Entity\\Usuario' . "\0" . 'idUsuario', '' . "\0" . 'App\\Entity\\Usuario' . "\0" . 'descNome', '' . "\0" . 'App\\Entity\\Usuario' . "\0" . 'numrCpf', '' . "\0" . 'App\\Entity\\Usuario' . "\0" . 'descEmail', '' . "\0" . 'App\\Entity\\Usuario' . "\0" . 'descSenha', '' . "\0" . 'App\\Entity\\Usuario' . "\0" . 'dataNascimento', '' . "\0" . 'App\\Entity\\Usuario' . "\0" . 'dataRegistro', '' . "\0" . 'App\\Entity\\Usuario' . "\0" . 'enderecos', '' . "\0" . 'App\\Entity\\Usuario' . "\0" . 'biometrias', '' . "\0" . 'App\\Entity\\Usuario' . "\0" . 'telefones', '' . "\0" . 'App\\Entity\\Usuario' . "\0" . 'tokens'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Usuario $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy::$lazyPropertiesDefaults as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @deprecated no longer in use - generated code now relies on internal components rather than generated public API
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getIdUsuario()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getIdUsuario();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIdUsuario', []);

        return parent::getIdUsuario();
    }

    /**
     * {@inheritDoc}
     */
    public function setIdUsuario($idUsuario)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIdUsuario', [$idUsuario]);

        return parent::setIdUsuario($idUsuario);
    }

    /**
     * {@inheritDoc}
     */
    public function getDescNome()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDescNome', []);

        return parent::getDescNome();
    }

    /**
     * {@inheritDoc}
     */
    public function setDescNome($descNome)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDescNome', [$descNome]);

        return parent::setDescNome($descNome);
    }

    /**
     * {@inheritDoc}
     */
    public function getNumrCpf()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNumrCpf', []);

        return parent::getNumrCpf();
    }

    /**
     * {@inheritDoc}
     */
    public function setNumrCpf($numrCpf)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNumrCpf', [$numrCpf]);

        return parent::setNumrCpf($numrCpf);
    }

    /**
     * {@inheritDoc}
     */
    public function getDescEmail()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDescEmail', []);

        return parent::getDescEmail();
    }

    /**
     * {@inheritDoc}
     */
    public function setDescEmail($descEmail)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDescEmail', [$descEmail]);

        return parent::setDescEmail($descEmail);
    }

    /**
     * {@inheritDoc}
     */
    public function getDescSenha()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDescSenha', []);

        return parent::getDescSenha();
    }

    /**
     * {@inheritDoc}
     */
    public function setDescSenha($descSenha)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDescSenha', [$descSenha]);

        return parent::setDescSenha($descSenha);
    }

    /**
     * {@inheritDoc}
     */
    public function getDataNascimento()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDataNascimento', []);

        return parent::getDataNascimento();
    }

    /**
     * {@inheritDoc}
     */
    public function setDataNascimento($dataNascimento)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDataNascimento', [$dataNascimento]);

        return parent::setDataNascimento($dataNascimento);
    }

    /**
     * {@inheritDoc}
     */
    public function getDataRegistro()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDataRegistro', []);

        return parent::getDataRegistro();
    }

    /**
     * {@inheritDoc}
     */
    public function setDataRegistro($dataRegistro)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDataRegistro', [$dataRegistro]);

        return parent::setDataRegistro($dataRegistro);
    }

    /**
     * {@inheritDoc}
     */
    public function getEnderecos()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getEnderecos', []);

        return parent::getEnderecos();
    }

    /**
     * {@inheritDoc}
     */
    public function getBiometrias()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getBiometrias', []);

        return parent::getBiometrias();
    }

    /**
     * {@inheritDoc}
     */
    public function getTelefones()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTelefones', []);

        return parent::getTelefones();
    }

    /**
     * {@inheritDoc}
     */
    public function getTokens()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTokens', []);

        return parent::getTokens();
    }

    /**
     * {@inheritDoc}
     */
    public function getTelefonePrincipal()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTelefonePrincipal', []);

        return parent::getTelefonePrincipal();
    }

    /**
     * {@inheritDoc}
     */
    public function getTelefoneOutro()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTelefoneOutro', []);

        return parent::getTelefoneOutro();
    }

}
